name: Actions Workflow
on: [push]
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List File
        run: |
          pwd
          ls
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-action@v1
        with: 
          who-to-greet: Edith
      - name: Log Greeting Time
        run: echo "${{steps.id.outputs.time}}"