name: Actions Workflow
on: [push]
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Action
        id: greet
        uses: actions/hello-javascript-action@v1
        with: 
          who-to-greet: Edith
      - name: Log Greeting Time
        run: echo "${{steps.id.outputs.time}}"